# Generated by Django 2.2 on 2019-04-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0001_initial'),
        ('post', '0002_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kredditor.Kredditor'),
        ),
    ]
