# Generated by Django 2.2 on 2019-04-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0002_auto_20190403_1506'),
        ('post', '0007_auto_20190409_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='kredditor.Kredditor'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='kredditor.Kredditor'),
        ),
    ]
