# Generated by Django 2.2 on 2019-04-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredditor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='kredditor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='kredditor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='kredditor',
            name='username',
        ),
    ]
