# Generated by Django 2.2 on 2019-04-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0002_auto_20190403_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredditor',
            name='following',
        ),
    ]
