# Generated by Django 2.2 on 2019-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0003_remove_kredditor_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredditor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
