# Generated by Django 2.2 on 2019-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subkreddit', '0002_auto_20190408_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkreddit',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
