# Generated by Django 2.2 on 2019-04-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0003_remove_kredditor_following'),
        ('subkreddit', '0003_auto_20190408_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subkreddit',
            name='user',
        ),
        migrations.AddField(
            model_name='subkreddit',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='kredditor.Kredditor'),
        ),
        migrations.AddField(
            model_name='subkreddit',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='kredditor.Kredditor'),
        ),
    ]
