# Generated by Django 2.2 on 2019-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredditor', '0002_auto_20190403_1506'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='commentdownvotes', to='kredditor.Kredditor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='commentupvotes', to='kredditor.Kredditor'),
        ),
    ]
